### ISSUE TITLE
Does not change fast

### ISSUE THREAD

**Issue by xbcc123** [fupengl/react-app-rewired-esbuild#1]
Does not change fast

![image](https://user-images.githubusercontent.com/21264579/145550491-ec4b006d-af63-4272-8936-b80a7f566fa0.png)

**Comment by fupengl** [comment]
> Does not change fast
> 
> ![image](https://user-images.githubusercontent.com/21264579/145550491-ec4b006d-af63-4272-8936-b80a7f566fa0.png)

里面的参数不要传,建议开发环境使用

**Comment by fupengl** [comment]
我这边是因为项目提及比较庞大,加上之后开发实时预览编译速度有大幅度的提升,生产模式打包不建议使用
