### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by anatoly-day-io** [fupengl/react-app-rewired-esbuild#3]
I get a screen with "ReferenceError: React is not defined" error
There is something about it in the readme but It is not clear what I should do to fix it.

**Comment by fupengl** [comment]
Added react introduction in the first line of the error file,Originally, `babel-plugin-react-app` handled this situation, but esbuild did not.

**Comment by fupengl** [comment]
It is recommended to use the development mode to ensure stability

**Comment by fupengl** [comment]
> I get a screen with "ReferenceError: React is not defined" error There is something about it in the readme but It is not clear what I should do to fix it.

Sorry, I didn't read the reply below carefully, can you check if there is a place where you forgot to introduce React at the top, or your react was external?

**Comment by shapeshifta78** [comment]
If you are using React 17 with the autoimport feature you need to use the provide Plugin as described here
https://github.com/privatenumber/esbuild-loader-examples/blob/52ca91b8cb2080de5fc63cc6e9371abfefe1f823/examples/react/webpack.config.js#L39-L41
