### ISSUE TITLE
How to tell if working?

### ISSUE THREAD

**Issue by jeffhu1** [fupengl/react-app-rewired-esbuild#5]
I followed the README but not sure if the performance I'm getting is what's promised - seems to take about the same time, is there any way to check if esbuild is being run correctly for the dev server / prod builds?

Seems much slower than Vite for devserver, but I would expect them to take roughly the same amount of time as they're both using esbuild.

**Comment by fupengl** [comment]
You can print the webpack configuration to see if it takes effect
You can build it to see the packaging time
The startup speed may not be improved significantly, but it will be more obvious when recompiling

**Comment by jeffhu1** [comment]
I see, thanks for the fast response! Do you happen to know how Vite achieves such fast cold start times then?

For reference, printing the webpack config it did indeed replace the babel-loader successfully 👍

**Comment by fupengl** [comment]
vite uses on-demand compilation, not just the performance improvement brought by esbuild
